repos:
  - repo: local
    hooks:
      - id: whitespace
        name: strip whitespace
        entry: ./strip_whitespace.sh
        language: system
        always_run: true
        pass_filenames: false
      - id: lint
        name: lint files
        entry: ./lint.sh
        language: system
        always_run: true
        pass_filenames: false
      - id: fuzz
        name: fuzz tests
        entry: ./fuzz.sh
        language: system
        always_run: true
        pass_filenames: false
      - id: devicetests
        name: select GPU tests
        entry: env GPU=1 PYTHONPATH="." pytest test/test_uops.py test/test_custom_function.py test/test_search.py
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: subset of TORCH tests
        entry: env PYTHONPATH="." TORCH=1 python3 -m pytest -n=4 test/unit/ test/test_ops.py test/test_dtype.py test/test_schedule.py test/test_custom_function.py test/test_assign.py test/test_symbolic_shapetracker.py
        language: system
        always_run: true
        pass_filenames: false
      - id: example
        name: multi device tests
        entry: python3 test/external/external_test_example.py
        language: system
        always_run: true
        pass_filenames: false
